### ISSUE TITLE
iPhone 6s Plus not recognized?

### ISSUE THREAD

**Issue by ahope1** [tihmstar/tsschecker#10]
I'm following [this tutorial](https://www.reddit.com/r/jailbreak/comments/5iom16/tutorial_mac_how_to_save_your_shsh2_blobs_step_by/) but getting this error:

`[Error] [TSSC] ERROR: device "iPhone8,2" is not in bbgcid.json, which means it's BasebandGoldCertID isn't documented yet.`
`If you own such a device please consider contacting @tihmstar (tihmstar@gmail.com) to get instructions how to contribute to this project.`
`[TSSR] WARNING: there was an error getting BasebandGoldCertID, continuing without requesting Baseband ticket`
`[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2`
`[TSSR] Sending TSS request attempt 1... success`
`Saved shsh blobs!`
`iOS 10.1 for device iPhone8,2 IS being signed!`

**Comment by stonegray** [comment]
Not having the BasebandGoldCertID is ok, it will successfully save the blobs anyway.

**Comment by ahope1** [comment]
Thanks, @stonegray!  

Btw, do you know if it's okay if my blobs are all 8KB in file size? Because they are.

**Comment by derobi** [comment]
if you double click the .shsh2 file and go to the bottom does it have a generator file

**Comment by ahope1** [comment]
@derobi I presume I'd need Xcode to be able to double-click a .shsh2 file, but I don't have it installed. But I can open the .shsh2 file in a text editor, and I see that at the end there's a key named "generator" with a string value that appears to consist of eight hexadecimal digits.

**Comment by derobi** [comment]
so your blob is good to go

**Comment by ahope1** [comment]
Ah, thanks @derobi! I'm not totally sure how .shsh2 blobs work, as you can probably tell!

**Comment by ahope1** [comment]
Is it important to save apnonces (whatever they are!) as well blobs?
