### ISSUE TITLE
possible bug in tss.c

### ISSUE THREAD

**Issue by acediac** [tihmstar/tsschecker#101]
There might be a potential bug in tss.c
Referring to version a391035  on 2 Jul (latest on github)

the **tss_request_send_raw** function (line 806) has a pointer to int named _response_lenth_ (sp?) as the 3rd parameter, but it is never set within the function.

[ Logical place would be at line 928:  

> *response_lenth = response->length;

 ]

**tss_request_send** function (line 934) actually calls **tss_request_send_raw** on line 945 and then uses the _responseLength_ from that call to calculate the tss_size (line 956), which will be incorrect if _responseLength_ is not set correctly.

I found this by debugging because I was getting null tss_response in tsschecker even though the response from apple servers was valid.

What I don't understand is how this ever worked for anyone??

**Comment by tihmstar** [comment]
Yes you're right. Just stumble across this myself yesterday.
fixed it with 62805e474982e78d378fea023c3469ffe7a5d078
