### ISSUE TITLE
tsschecker no longer works with iOS 11.0.1

### ISSUE THREAD

**Issue by JamesMaloney** [tihmstar/tsschecker#102]
When I try to save shsh2 blobs for iOS 11.0.1 (for both iPad6,4 and iPhone10,5), tsschecker tells me that version of iOS doesn't exist. Other versions like 11.0 are fine though.
Maybe Apple changed something on their server?
Here is the log:

E:\Documenti\Tools\Apple\tsschecker v170>"E:\Documenti\Tools\Apple\tsschecker v170\tsschecker_windows.exe" -s -d iPad6,4 -e 001048CE1087C226 --save-path C:\Users\AceOfSpades\shsh2\iPad6,4\AceOfSpades -i 11.0.1
Version: af9b9f2998bdeca7ece0829c2e718ae747745750 - 170
[TSSC] manually specified ecid to use, parsed "001048CE1087C226" to dec:4583649505165862 hex:1048ce1087c226
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] ERROR: either device iPad6,4 does not exist, or there is no iOS 11.0.1 for it.

iOS 11.0.1 for device iPad6,4 IS NOT being signed!

P.S.: I'm using version 170 of tsschecker as I keep getting the same error with every device/iOS on version 212, which is:
[Error] [LFZP] failed to download file (-10)

**Comment by 2Klasic** [comment]
have you tried to do it as -l --nocahe instead of -i 11.0.1

**Comment by JamesMaloney** [comment]
Yeah, you're right, that fixed it.
I was sure that I had already tried this and failed, but I was wrong apparently.
Thanks and sorry for the bother
