### ISSUE TITLE
BasebandGoldCertID

### ISSUE THREAD

**Issue by Neal248** [tihmstar/tsschecker#104]
"iPhone9,3" is not in bbgcid list

How can I help getting the BasebandGoldCertID?

**Comment by 2Klasic** [comment]
here is a post from tihmstar on what to do in this situation 

http://blog.tihmstar.net/2017/01/basebandgoldcertid-not-found-please.html

**Comment by Neal248** [comment]
For iPhone9,3 (iPhone 7)

BasebandGoldCertId:              1421084145

**Comment by 2Klasic** [comment]
send it to tihmstar via his email tihmstar@gmail.com

**Comment by 2Klasic** [comment]
you can now close this issue
