### ISSUE TITLE
Hex ECID from iTunes without A-F inside will be converted to hex again

### ISSUE THREAD

**Issue by Alex793** [tihmstar/tsschecker#11]
Hi, just discovered this night one of my iPad have an hex ECID from iTunes without any A-F characters inside, so if you put this value into tsschecker it think it's a DEC value and it will be converted again to an other wrong HEX value.

No problem if you use the DEC value converted from this rare HEX ECID, it will be converted in tsschecker to the good HEX ECID.

Also I don't know if it's important but my hex ECID without A-F inside have 13 digits in hex and 15 in dec while my hex ECID from my other iPad with A-F inside have 14 digits in hex and 16 in dec.

;)

**Comment by tihmstar** [comment]
Fixed in https://github.com/tihmstar/tsschecker/commit/14d1631db9930028613fc767411a33f2456eb2bb
If your hex ecid only contains digits, be sure to prefix "0x" (-e 0x123456 ).
