### ISSUE TITLE
iOS 11.2.5 / 15D60 Cannot sign ...

### ISSUE THREAD

**Issue by avivmaman** [tihmstar/tsschecker#110]
`[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] ERROR: could not get url for device iPhone9,4 on iOS 15D60

[Error] [TSSC] checking tss status failed!`

Tss by conan1 is working fine .

**Comment by 1Conan** [comment]
Remove the cached firmwares.json
