### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by vladut123** [tihmstar/tsschecker#111]
Unable to compile tsschecker

**Comment by waja** [comment]
Okay ... it would be very helpful if you can provide further information. Just shouting "this doesn't work" isn't very helpful, for nobody.

**Comment by vladut123** [comment]
What further information

**Comment by vladut123** [comment]
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .gitMaking all in tsschecker
gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/local/include -I/usr/local/include -I/usr/local/Cellar/libzip/1.4.0/include   -I/usr/local/include  -I../external/jssy/jssy/ -g -O2 -std=c11 -MT tsschecker-tsschecker.o -MD -MP -MF .deps/tsschecker-tsschecker.Tpo -c -o tsschecker-tsschecker.o `test -f 'tsschecker.c' || echo './'`tsschecker.c
tsschecker.c:32:2: warning: TODO verify these values are actually correct for all devices (iPhone7) [-W#warnings]
#warning TODO verify these values are actually correct for all devices (iPhone7)
 ^
tsschecker.c:1048:2: warning: print devices function doesn't actually check if devices are sorted. it assues they are
      sorted in json [-W#warnings]
#warning print devices function doesn't actually check if devices are sorted. it assues they are sorted in json
 ^
2 warnings generated.
mv -f .deps/tsschecker-tsschecker.Tpo .deps/tsschecker-tsschecker.Po
gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/local/include -I/usr/local/include -I/usr/local/Cellar/libzip/1.4.0/include   -I/usr/local/include  -I../external/jssy/jssy/ -g -O2 -std=c11 -MT tsschecker-tss.o -MD -MP -MF .deps/tsschecker-tss.Tpo -c -o tsschecker-tss.o `test -f 'tss.c' || echo './'`tss.c
mv -f .deps/tsschecker-tss.Tpo .deps/tsschecker-tss.Po
gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/local/include -I/usr/local/include -I/usr/local/Cellar/libzip/1.4.0/include   -I/usr/local/include  -I../external/jssy/jssy/ -g -O2 -std=c11 -MT tsschecker-download.o -MD -MP -MF .deps/tsschecker-download.Tpo -c -o tsschecker-download.o `test -f 'download.c' || echo './'`download.c
mv -f .deps/tsschecker-download.Tpo .deps/tsschecker-download.Po
gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/local/include -I/usr/local/include -I/usr/local/Cellar/libzip/1.4.0/include   -I/usr/local/include  -I../external/jssy/jssy/ -g -O2 -std=c11 -MT tsschecker-main.o -MD -MP -MF .deps/tsschecker-main.Tpo -c -o tsschecker-main.o `test -f 'main.c' || echo './'`main.c
mv -f .deps/tsschecker-main.Tpo .deps/tsschecker-main.Po
make[2]: *** No rule to make target `../external/jssy/jssy/jssy.c', needed by `libjssy_a-jssy.o'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
