### ISSUE TITLE
buildmanifest.plist failed to download, win7 x64

### ISSUE THREAD

**Issue by cybppp** [tihmstar/tsschecker#117]
Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
[TSSC] manually specified ecid to use, parsed "42D6C24A3C3BA" to dec:11758424012
72762 hex:42d6c24a3c3ba
[TSSC] manually specified apnonce to use, parsed "603be133ff0bdfa0f83f21e74191cf
6770ea43bb" to hex:603be133ff0bdfa0f83f21e74191cf6770ea43bb
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 11.2.6 build 15D100
[TSSC] opening Buildmanifest for iPhone8,1_11.2.6_15D100
[LFZP] downloading BuildManifest.plist from http://appldnld.apple.com/ios11.2.6/
091-69900-20180220-063C9194-1331-11E8-B0A3-28A2E0A71A1F/iPhone_4.7_11.2.6_15D100
_Restore.ipsw

[A[J100 [=====================================================================
==============================>]
[A[J006 [=====>
                               ]
[A[J024 [=======================>
                               ]
[A[J031 [==============================>
                               ]
[A[J049 [================================================>
                               ]
[A[J056 [=======================================================>
                               ]
[A[J093 [=====================================================================
=======================>       ]
[A[J100 [=====================================================================
==============================>]
[Error] [LFZP] failed to download file (-10)
[Error] [TSSC] ERROR: could not get BuildManifest for firmwareurl http://appldnl
d.apple.com/ios11.2.6/091-69900-20180220-063C9194-1331-11E8-B0A3-28A2E0A71A1F/iP
hone_4.7_11.2.6_15D100_Restore.ipsw

iOS 11.2.6 for device iPhone8,1 IS NOT being signed!

**Comment by cnnmpc** [comment]
`-d iPhone8,1 --boardconfig n71map -e xxxxxxxxxxxxxx  -i 11.2.6 -s`

**Comment by tihmstar** [comment]
No support for windows
