### ISSUE TITLE
Version: 63b2de66d72c1eb57e1e5559102bdfa144717787 - 252 Segmentation Fault (core dumped))

### ISSUE THREAD

**Issue by sandhoners123** [tihmstar/tsschecker#119]
tss checker version: 63b2de66d72c1eb57e1e5559102bdfa144717787 - 252 segfaults when you try to run "tsschecker --beta -d -l --nocache iPad5,3". I am using Ubuntu cosmic cuttlefish (18.10)

**Comment by cvanelteren** [comment]
Same issue running antergos

**Comment by beret** [comment]
[tsschecker r252.63b2de6 segfault strace excerpt.txt](https://github.com/tihmstar/tsschecker/files/2391544/tsschecker.r252.63b2de6.segfault.strace.excerpt.txt)

Here's an strace on Arch 64 (linux-lts), last library read appears to be udev and then it crashes.
I can also confirm this has been around for months on my setup. I've rebuilt the latest master (and some dependencies libfragmentzip-git  libirecovery-git  libplist-git) with no change.

**Comment by cvanelteren** [comment]
Got it to run with 
    `env LD_PRELOAD=/usr/lib/libcurl.so.3  /path/to/tsschecker`

**Comment by beret** [comment]
After my installation of `libcurl-compat` and a rebuild of `tsschecker` from git master:
```
# env LD_PRELOAD=/usr/lib/libcurl.so.3 /usr/bin/tsschecker [parameters]
/usr/bin/tsschecker: /usr/lib/libcurl.so.3: no version information available (required by /usr/bin/tsschecker)
/usr/bin/tsschecker: /usr/lib/libcurl.so.3: no version information available (required by /usr/lib/libfragmentzip.so.0)
Version: 63b2de66d72c1eb57e1e5559102bdfa144717787 - 252
Segmentation fault (core dumped)
```

**Comment by cvanelteren** [comment]
@beret there is something (obviously) wrong with you curl. Do you have multiple installed? Try to remove them and reinstall libcurl-openssl.

**Comment by cvanelteren** [comment]
Segfault magically reappared again today. Is there any permanent fix for this?
