### ISSUE TITLE
Error on downloading iPhone X shsh2 with Coolstar’s nonces

### ISSUE THREAD

**Issue by Tizioincognit0** [tihmstar/tsschecker#120]
I’m trying download iPhone X shsh2 using Coolstar’s nonces on macOS High Sierra 10.13.5 but, after the download of “BuildManifest.plist”, i have this error:

[Error] [TSSR] parsed APNoncelen != requiredAPNoncelen (32 != 20)
[Error] [TSSR] failed to populate tss request
[Error] [TSSR] faild to build tssrequest

[Error] [TSSC] checking tss status failed!

**Comment by Jables-Supreme** [comment]
Getting the same error on iPhone 8+ with Coolstar's nonces.

**Comment by ianrod30** [comment]
Same issue on my iP8+ with Coolstar's nonces.

**Comment by Kermad** [comment]
Same issue with iPhone 8+ with Coolstar's nonces. this is sad

**Comment by tihmstar** [comment]
Insufficient information for analysing the issue

**Comment by Tizioincognit0** [comment]
Insufficient?

**Comment by tihmstar** [comment]
Yes, insufficient.
Next time please include:
- What version of tsschecker are you using? (version number and commit hash)
- What device are you using? (model and boardconfig)
- Full command you used to invoke tsschecker

And most important:
- Instructions on how to reproduce the error


Also a short explanation what "Coolstar’s nonces" are would be helpful.

**Comment by Tizioincognit0** [comment]
This is not necessary: finally I solved using the GUI application “blobsaver” which is the better way to save shsh2 blobs.
