### ISSUE TITLE
Latest compiled version does not contain exe

### ISSUE THREAD

**Issue by s1h4d0w** [tihmstar/tsschecker#121]
Just downloaded the zip with the latest compiled version, but it only contains the mac and linux versions. Disabled my virusscanner to be sure, still nothing sadly.

![image](https://user-images.githubusercontent.com/5654654/41107995-c238165e-6a73-11e8-8c3b-54c335659d2c.png)

**Comment by tihmstar** [comment]
windows support was dropped a while ago. 
mainly because compiling for windows is such a pain.
