### ISSUE TITLE
says ios 11.4 isnt being signed by iphone 9,4..... it is the latest version tho

### ISSUE THREAD

**Issue by ranscapture** [tihmstar/tsschecker#124]
i entered my device info correctly and it gave me:

C:\Users\Ran\Downloads\tsschecker-latest>tsschecker_windows -B D111AP -e A454C00BA003A -l -s
Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
[TSSC] manually specified ecid to use, parsed "A454C00BA003A" to dec:2890942499127354 hex:a454c00ba003a
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest iOS: 11.4
[TSSC] got firmwareurl for iOS 11.4 build 15F79
[TSSC] opening Buildmanifest for iPhone9,4_11.4_15F79
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2018/ios/091-64896-20180529-3B0E42BC-5ABE-11E8-A675-F157A3E35D9E/iPhone_5.5_P3_11.0_11.4_15F79_Restore.ipsw

[A[J100 [===================================================================================================>]
[A[J002 [=>                                                                                                  ]
[A[J050 [=================================================>                                                  ]
[A[J063 [==============================================================>                                     ]
[A[J068 [===================================================================>                                ]
[A[J100 [===================================================================================================>]
[Error] [LFZP] failed to download file (-10)
[Error] [TSSC] ERROR: could not get BuildManifest for firmwareurl http://updates-http.cdn-apple.com/2018/ios/091-64896-20180529-3B0E42BC-5ABE-11E8-A675-F157A3E35D9E/iPhone_5.5_P3_11.0_11.4_15F79_Restore.ipsw

iOS 11.4 for device iPhone9,4 IS NOT being signed!

C:\Users\Ran\Downloads\tsschecker-latest>

**Comment by tihmstar** [comment]
Windows is not supported
