### ISSUE TITLE
Unhandled status code 128

### ISSUE THREAD

**Issue by palmerc** [tihmstar/tsschecker#125]
TSS starts off with success but then bumps into unhandled status code 128 on the later requests. Is this a known issue? I've noticed this behaviour in both my builds and the official download. I'll get around to debugging this later, but for now maybe someone already knows the answer.

mac:devel palmerc$ mkdir -p blobs/${ECID}; ./tsschecker_macos --boardconfig n53ap --ecid ${ECID} --save-path blobs/${ECID} --ios 11.4 --save 
Version: 62805e474982e78d378fea023c3469ffe7a5d078 - 247
[TSSC] manually specified ecid to use, parsed "${ECID}" to dec:XXXX hex:ABCD
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 11.4 build 15F79
[TSSC] opening Buildmanifest for iPhone6,2_11.4_15F79
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2018/ios/091-64669-20180529-3B06872A-5ABE-11E8-856C-E557A3E35D9E/iPhone_4.0_64bit_11.4_15F79_Restore.ipsw
100 [===========================================================================047 [==============================================>                            059 [==========================================================>                078 [===========================================================================100 [===================================================================================================>]
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] User specified not to request a Baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 2... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 3... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 4... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 5... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 6... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 7... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 8... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 9... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 10... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 11... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 12... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 13... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 14... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 15... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[Error] ERROR: TSS request failed: SSL: no alternative certificate subject name matches target host name '17.111.103.15' (status=128)
Saved shsh blobs!
iOS 11.4 15F79 IS signed!

iOS 11.4 for device iPhone6,2 IS being signed!

**Comment by D3m3rion** [comment]
Any news on this? I'm running into the same problem with my iPad, but not my iPhone

**Comment by tihmstar** [comment]
As you can see the command return success (as seen with ```echo $?``` returning 0).
It still saves the APTicket correctly, you can safely ignore this
```
tMBP:kk tihmstar$ tsschecker --boardconfig n53ap -l -s
Version: 3efa4ac03e52e8482fca0ee9f68479034e84a881 - 261
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest iOS: 12.1
[TSSC] got firmwareurl for iOS 12.1 build 16B92
[TSSC] opening Buildmanifest for iPhone6,2_12.1_16B92
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2018FallFCS/fullrestores/091-91318/964164AA-D4BE-11E8-B0E4-880CD9066485/iPhone_4.0_64bit_12.1_16B92_Restore.ipsw
100 [===================================================================================================>]
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] User specified not to request a Baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 2... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 3... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 4... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 5... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 6... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 7... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 8... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 9... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 10... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 11... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to http://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 12... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 13... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 14... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[TSSR] Request URL set to https://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 15... failure
[Error] ERROR: tss_send_request: Unhandled status code 128
[Error] ERROR: TSS request failed: SSL: no alternative certificate subject name matches target host name '17.111.103.15' (status=128)
Saved shsh blobs!
iOS 12.1 16B92 IS signed!

iOS 12.1 for device iPhone6,2 IS being signed!
tMBP:kk tihmstar$ echo $?
0
tMBP:kk tihmstar$ ls
5004093866056209_iPhone6,2_n53ap_12.1-16B92_01a392755836bf07745d322ba11330e7a4c5d64d.shsh2
```
