### ISSUE TITLE
remove dependency on ipsw.me ?

### ISSUE THREAD

**Issue by jkister** [tihmstar/tsschecker#141]
it would be nice to have another mechanism to get firmware info besides ipsw.me

```
$ tsschecker_linux \
   -d iPhone8,1 \
   -B n71map \
   -e 5634301580782630 \
   --list-ios --latest --nocache
Version: 62805e474982e78d378fea023c3469ffe7a5d078 - 247
[TSSC] manually specified ecid to use, parsed "5634301580782630" to dec:5634301580782630 hex:14045e1047ac26
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[Error] failed to download file from=https://api.ipsw.me/v2.1/firmwares.json/condensed to=/tmp/firmware.json CURLcode=28
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] parsing firmware.json failed
```

i also see

```
$ wget --timeout=240 https://api.ipsw.me/v2.1/firmwares.json/condensed
--2019-08-26 14:46:38--  https://api.ipsw.me/v2.1/firmwares.json/condensed
Resolving api.ipsw.me (api.ipsw.me)... 104.24.26.50, 104.24.27.50, 2606:4700:20::6818:1a32, ...
Connecting to api.ipsw.me (api.ipsw.me)|104.24.26.50|:443... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2019-08-26 14:47:12 ERROR 502: Bad Gateway.
```

which obviously does not get the file.

**Comment by afit** [comment]
It would be possible to fall back on DeviceIdentifier API where ipsw.me isn't available, as it provides data in the same format: [OTA feed](https://di-api.reincubate.com/v1/firmware/ota-feed/), [non-OTA feed](https://di-api.reincubate.com/v1/firmware/full-feed/), [more info](https://reincubate.com/support/deviceidentifier/apple-firmware-data/#firmware-feed)). It's a two-line patch of `FIRMWARE_JSON_URL` and `FIRMWARE_OTA_JSON_URL`.

**Comment by s0uthwest** [comment]
@afit outdated

**Comment by afit** [comment]
Ah, thanks @s0uthwest. The newer builds weren't being pushed to the non-OTA feed. I've resolved that.
