### ISSUE TITLE
Downloading iOS 13.0 doesn't work

### ISSUE THREAD

**Issue by 0ki** [tihmstar/tsschecker#143]
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2019FallFCS/fullrestores/091-99502/xxxxxxxxx/iPhone_4.0_64bit_13.1_17A844_Restore.ipsw

[Error] [LFZP] failed to open url
[Error] [TSSC] ERROR: could not get BuildManifest for firmwareurl http://updates-http.cdn-apple.com/2019FallFCS/fullrestores/091-99502/xxxxxxx/iPhone_4.0_64bit_13.1_17A844_Restore.ipsw

**Comment by 0ki** [comment]
Old version segfaulted, current version just doesn't work. https://github.com/TSSSaver/TSSSaver have allegedly fixed it.

**Comment by nadavcoh** [comment]
This is fixed by https://github.com/tihmstar/libfragmentzip/commit/ce600b161683281f48ee8c0bc5944b30c1fbc01a
You need to compile libfragmentzip and tsschecker to use this.

**Comment by 0ki** [comment]
libfragmentzip is not a dynamically linked dependency.
Why doesn't it work for compiled versions found at 
http://api.tihmstar.net/builds/tsschecker/tsschecker-latest.zip ?

**Comment by nadavcoh** [comment]
It is confusing as it has the word "latest" in the name, but that link points to a binary compiled from a commit made in 2017, so I wouldn't expect it to contain a fix made 3 days ago.

**Comment by 0ki** [comment]
ooh, @s0uthwest! how about an update on the "latest" please? ;)

**Comment by nadavcoh** [comment]
I'm sure s0uthwest and tihmstar have better things to do than to compile binaries for us.. just compile them yourself

**Comment by 0ki** [comment]
I would, but what's the point since I don't have access to api.thumstar.net to replace the non-latest one with the correct one?
