### ISSUE TITLE
Ipad7,11

### ISSUE THREAD

**Issue by asislife20** [tihmstar/tsschecker#147]
cant save blobs for ipad 7th gen, get error saying its unable to extract build manifest.

**Comment by s0uthwest** [comment]
It’s ipsw.me bug; it downloaded buildmanifest for iPad7,1(2,3,4), not 7,11/7.12.

**Comment by DanTheMann15** [comment]
unfortunately the only way around this (for all platforms) is to manually download the IPSW, and extract the buildmanifest using 7zip.

but if you can compile and use partialzipbrowser, you could get the buildmanifest using that without having to download the whole IPSW.

**Comment by asislife20** [comment]
Im able to save blobs now, with the jailbreak bot, and using the system info tweak both work.
