### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [tihmstar/tsschecker#15]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [win_path_get](https://github.com/tihmstar/tsschecker/blob/fc1c2d506f41834033014e20311ecb444135d87b/tsschecker/tsschecker.c#L51)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string") ⇒ [main](https://github.com/tihmstar/tsschecker/blob/14d1631db9930028613fc767411a33f2456eb2bb/tsschecker/main.c#L290)

**Comment by tihmstar** [comment]
Not sure what kind of error handling you're talking about.
If you have a suggestion, please make a pull request.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "More checking for return values") a bit more.
Would you like to detect every error situation as early as possible?
