### ISSUE TITLE
tsschecker v305 unable to parse firmware.json on Windows.

### ISSUE THREAD

**Issue by DanTheMann15** [tihmstar/tsschecker#153]
I can't really say much about this little error, but here it goes.

I can successfully compile tsschecker on Windows 64bit with Mingw64 through either msys2 or Cygwin64 without any problems.

but when you attempt to use the program to save APTickets, it can download the firmware.json file just fine from ipsw.me but then when it tries to parse the file, it errors-out. (see screenshot)

![7d77d61a2574bd1ec148871235f4a798](https://user-images.githubusercontent.com/51378736/75416323-0a896200-58fc-11ea-88a3-4130725e81aa.jpg)

I have a small hunch that this problem might lie with either jssy or libfragmentzip, but i'm not 100% sure, i think @xybp888 knows the answer since he is a master at building this for Windows.

the only way you can save tickets with this build of tsschecker that anyone can compile on Windows is to manually provide a BuildManifest using the "-m" or "--build-manifest" parameter.

doing it that way, it works like a charm.

**Comment by s0uthwest** [comment]
It’s problem with libfragmentzip, of course. And maybe problems with ipsw.me.

**Comment by haen7** [comment]
I had the same problem with v305 on Mingw64. This patch solved parsing error for me.
````diff
diff --git a/configure.ac b/configure.ac
index e9e2384..4d8ca11 100644
--- a/configure.ac
+++ b/configure.ac
@@ -15,7 +15,7 @@ esac
 
 # Checks for programs.
 AC_PROG_CC
-CFLAGS+=" -std=gnu11"
+CFLAGS+=" -std=c11"
 AC_PROG_INSTALL
 AC_PROG_LIBTOOL
 AC_CONFIG_MACRO_DIRS([m4])
diff --git a/tsschecker/tsschecker.c b/tsschecker/tsschecker.c
index 84efc0a..d08e54b 100644
--- a/tsschecker/tsschecker.c
+++ b/tsschecker/tsschecker.c
@@ -14,14 +14,14 @@
 #include <time.h>
 #include <stdio.h>
 
-#include <libfragmentzip/libfragmentzip.h>
-#include <libirecovery.h>
-
 #include "tsschecker.h"
 #include "debug.h"
 #include "download.h"
 #include "tss.h"
 
+#include <libfragmentzip/libfragmentzip.h>
+#include <libirecovery.h>
+
 #ifdef __APPLE__
 #   include <CommonCrypto/CommonDigest.h>
 #   define SHA1(d, n, md) CC_SHA1(d, n, md)
````

**Comment by s0uthwest** [comment]
@haen7 give a screenshot of fixing problem, please

**Comment by haen7** [comment]
> @haen7 give a screenshot of fixing problem, please

![Annotation 2020-03-13 113252](https://user-images.githubusercontent.com/20773117/76601744-cebae300-651e-11ea-9c52-92f449e683ff.png)

**Comment by DanTheMann15** [comment]
heh, nice quick patch... i'm going to test it and recompile now :3.

**Comment by DanTheMann15** [comment]
after playing around a little more with tsschecker's source, i found that this alone can achieve the same result.

> 
> ```diff
> diff --git a/tsschecker/tsschecker.c b/tsschecker/tsschecker.c
> index 84efc0a..d08e54b 100644
> --- a/tsschecker/tsschecker.c
> +++ b/tsschecker/tsschecker.c
> @@ -14,14 +14,14 @@
>  #include <time.h>
>  #include <stdio.h>
>  
> -#include <libfragmentzip/libfragmentzip.h>
> -#include <libirecovery.h>
> -
>  #include "tsschecker.h"
>  #include "debug.h"
>  #include "download.h"
>  #include "tss.h"
>  
> +#include <libfragmentzip/libfragmentzip.h>
> +#include <libirecovery.h>
> +
>  #ifdef __APPLE__
>  #   include <CommonCrypto/CommonDigest.h>
>  #   define SHA1(d, n, md) CC_SHA1(d, n, md)
> ```

**Comment by DanTheMann15** [comment]
this fix is now implemented in the latest merges, so i can finally close this issue.
