### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by grkka** [tihmstar/tsschecker#16]
[Error] [TSSC] ERROR: device "iPhone8,2" is not in bbgcid.json, which means it's BasebandGoldCertID isn't documented yet.
If you own such a device please consider contacting @tihmstar (tihmstar@gmail.com) to get instructions how to contribute to this project.
[TSSR] WARNING: there was an error getting BasebandGoldCertID, continuing without requesting Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
Saved shsh blobs!
 
iOS 10.2 for device iPhone8,2 IS being signed!

Is this "Error" normal?

**Comment by tihmstar** [comment]
If you want to contribute please check your BasebandGoldCertID with redsn0w and send me an email.

**Comment by grkka** [comment]
@tihmstar email sent.
