### ISSUE TITLE
/tmp/firmwares.json not deleted automatically, causing newer iOS versions to be not found

### ISSUE THREAD

**Issue by 0xallie** [tihmstar/tsschecker#166]
It seems like tsschecker doesn't delete `/tmp/firmwares.json` automatically, so it was failing to detect iOS versions past 14.0 for me. It took me a while to figure out that I had to manually delete this file.

```
❯ lsb_release -d
Description:    Debian GNU/Linux 10 (buster)
❯ tsschecker --version
Version: bdeed20aadb644239a2a50aae15af08a18b44d81 - 319
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
```

**Comment by DanTheMann15** [comment]
you can also pass `--nocache` to tsschecker to redownload firmwares.json, you don't necessarily have to manually delete it.

**Comment by tihmstar** [comment]
In the new rewrite "nocache" is now the default. Add "-c" or "--cache" if you want to use cache
