### ISSUE TITLE
iPhone 4 (model iPhone3,2) with iOS 7.1.2 check fails

### ISSUE THREAD

**Issue by mologie** [tihmstar/tsschecker#17]
Hello, I found that the following command fails, although iOS 7.1.2 is being signed and is the latest supported firmware for the iPhone 4.

```
$ tsschecker -i 7.1.2 -d iPhone3,1 -s -e <snip> --save-path .
[TSSC] manually specified ecid to use, parsed "<snip>" to dec:<snip> hex:<snip>
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 7.1.2 build 11D257
[TSSC] opening Buildmanifest for iPhone3,1_7.1.2
[LPZP] downloading BuildManifest.plist from http://appldnld.apple.com/iOS7.1/031-4812.20140627.cq6y8/iPhone3,1_7.1.2_11D257_Restore.ipsw
100 [===================================================================================================>]
[TSSC] opening bbgcid.json
[DOWN] downloading file http://api.tihmstar.net/bbgcid?condensed=1
[JSON] counting elements
[JSON] parsing elements
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure

iOS 7.1.2 for device iPhone3,1 IS NOT being signed!
```

**Comment by derobi** [comment]
try to run the command like this instead
tsschecker -d iPhone3,1 -e ECID# -s ~/Desktop -l if you do it with the -l command it will grab the latest blobs for the device no need to specify with -i since 7.1.2 is the only blob being signed for that device

**Comment by mologie** [comment]
Thank you for your suggestion @derobi, but this had no effect. The log now says `[TSSC] selecting latest iOS: 7.1.2` in addition to the above log entries, but the error remains.

**Comment by tihmstar** [comment]
That's weird. It's probably a bug introduced when i updated to get correct iOS10 tickets. 
I'll look into that.

**Comment by MarkVillacampa** [comment]
I'd suggest trying with the v1.0 release: https://github.com/tihmstar/tsschecker/releases/tag/v1.0

I was able to download shsh for my iPad2,2 9.3.5 using it as I mentiones in #29

**Comment by tihmstar** [comment]
Looks like it's an issue with the baseband tickets. Works for me if i skip requesting BBTickets with -b
Still looking into the actual problem

**Comment by mrdc** [comment]
tihmstar, looks like the issue is here:

https://github.com/tihmstar/tsschecker/blob/master/tsschecker/tsschecker.c#L117
https://github.com/tihmstar/tsschecker/blob/master/tsschecker/tsschecker.c#L137

BasebandGoldCertID is wrong for iPad 2,2 and iPhone 3,1.
My iPad 2,2 shows in redsn0w also 257, but for sure it's wrong as it's too short...

**Comment by mrdc** [comment]
Hi!

Is there any way to save shsh2 for baseband for iPad 2,2? I'm not able to save it: "iOS 9.3.5 13G36 IS NOT signed!" if I run it without "-b"
