### ISSUE TITLE
tsschecker support to generate  the previous shsh without saving it.

### ISSUE THREAD

**Issue by Sunrier** [tihmstar/tsschecker#175]
Hi,tihmstar:
Your tsschecker is very great!
Do you know the process of generating shsh for iPhone?
If you know that you can try to issue new version to generate the previous shsh without saving it.
If there are any difficulties,try to can solve them with us.
Because it's trouble to save shsh every time.
Only when we use it and then  to be generated it.
We will expect your new version to support it.

**Comment by tihmstar** [comment]
I don't even know what any of this means
