### ISSUE TITLE
How do you actually compile and install it?

### ISSUE THREAD

**Issue by Pineconium** [tihmstar/tsschecker#177]
There's no install instructions, and using make won't work as it can't find a makefile.

**Comment by tihmstar** [comment]
If you can't figure out how to compile, i recommend to download the statically linked pre-build binary from releases here: https://github.com/tihmstar/tsschecker/releases/latest.
I set up CI for that very recently.

To answer your question, the procedure is:
1) `./autogen.sh`
2) `make -j`
3) `sudo make install`

Provided you have all required dependencies installed.
If any dependency is missing, the first step will tell you more. The dependencies are build and installed the same way.
