### ISSUE TITLE
Latest build downloading executables containing html

### ISSUE THREAD

**Issue by Alteration** [tihmstar/tsschecker#18]
Recently downloaded the files from the link to latest build, noticing the windows and linux options weren't working i opened the linux executable up in a text editor and the contents is just some html

> <body><h2>HTTP ERROR 404</h2>
> <p>Problem accessing /job/tsschecker/target=idevice-linux/lastSuccessfulBuild/artifact/tsschecker_tool. Reason:
> <pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

**Comment by tihmstar** [comment]
Should be fixed by now
