### ISSUE TITLE
10.2 Not Signed?

### ISSUE THREAD

**Issue by jmarkewicz** [tihmstar/tsschecker#19]
`C:\Users\Jake\Desktop\blobs>tsschecker.exe -d iPhone9,4 -e 11684A08884D26 -i 10.2 --buildid 14C92 -s --nocache
[TSSC] manually specified ecid to use, parsed "11684A08884D26" to dec:4899741784100134 hex:11684a08884d26
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 10.2 build 14C92
[TSSC] opening Buildmanifest for iPhone9,4_14C92
[LFZP] downloading BuildManifest.plist from http://appldnld.apple.com/ios10.2seed/031-93593-20161207-616AF724-BBD8-11E6-B29E-8D7FE47229E1/iPhone_7Plus_10.2_14C92_Restore.ipsw

[A[J100 [===================================================================================================>]
[A[J008 [=======>                                                                                            ]
[A[J089 [========================================================================================>           ]
[A[J098 [=================================================================================================>  ]
[A[J100 [===================================================================================================>]
[Error] iPhone7 device detected! Automatic generator->nonce calculation failed. Please manually specify an apnonce with len=32
[Error] [TSSR] failed to populate tss request
[Error] [TSSR] faild to build tssrequest

Build 14C92 for device iPhone9,4 IS NOT being signed!`

**Comment by BryanSuero** [comment]
[Check this out](https://twitter.com/tihmstar/status/815921105714221056)
