### ISSUE TITLE
Permission denied with latest tsschecker

### ISSUE THREAD

**Issue by chesstu** [tihmstar/tsschecker#25]
Hi, I feel like the answer is right in may face but I can't seem to find it !

Lates version of compiled tsschecker gives me a 'permission denied' error.
If I tried an older version that I downloaded previously it works just fine.
What I' mI dong wont this time ?? !!

EDIT: latest version that would work form here : [https://github.com/tihmstar/tsschecker/releases](https://github.com/tihmstar/tsschecker/releases) is version 1.0.6
Thank y'all ;)

<img width="897" alt="2017-01-05_10 50 03" src="https://cloud.githubusercontent.com/assets/3819492/21707003/530cb068-d399-11e6-8eae-fbcf88b3eb2c.png">

**Comment by tihmstar** [comment]
Binaries are shipped without executable flag. This wasn't really added purposely, but this is something i definetly wanna keep. You need to manually set executable flag with chmod +x.
Please use google next time.

**Comment by chesstu** [comment]
Thank you. I new my brain was stuck at something. 
Believe me, I tried Google, but I honestly didn't find anything regarding changing permission to executable.

But you're right, I should've know better.
My bad.

Thanks once again.
