### ISSUE TITLE
Can't save iPhone 7 blobs, even with latest version.

### ISSUE THREAD

**Issue by BlackGeekTutorial** [tihmstar/tsschecker#28]
> MBP-di-Andrea:Debug benti$ tsschecker -d iPhone9,4 -i 10.2 --buildid 14C92 --boardconfig bdid -s --apnonce 603be133ff0bdfa0f83f21e74191cf6770ea43bb --sepnonce 603be133ff0bdfa0f83f21e74191cf6770ea43bb --save-path /Users/benti/bigumbrella/shsh2 -e MY_ECID --nocache
> Version: af9b9f2998bdeca7ece0829c2e718ae747745750 - 170
> [TSSC] manually specified ecid to use, parsed "MY_ECID" to dec: MY_ECID hex: MY_ECID
> [TSSC] manually specified apnonce to use, parsed "603be133ff0bdfa0f83f21e74191cf6770ea43bb" to hex:603be133ff0bdfa0f83f21e74191cf6770ea43bb
> [TSSC] manually specified sepnonce to use, parsed "603be133ff0bdfa0f83f21e74191cf6770ea43bb" to hex:603be133ff0bdfa0f83f21e74191cf6770ea43bb
> [TSSC] opening firmware.json
> [DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
> [JSON] counting elements
> [JSON] parsing elements
> [TSSC] got firmwareurl for iOS 10.2 build 14C92
> [TSSC] opening Buildmanifest for iPhone9,4_14C92
> [LFZP] downloading BuildManifest.plist from http://appldnld.apple.com/ios10.2seed/031-93593-20161207-616AF724-BBD8-11E6-B29E-8D7FE47229E1/iPhone_7Plus_10.2_14C92_Restore.ipsw
> 100 [===================================================================================================>]
> [Error] [TSSR] Error: could not get id0
> [Error] [TSSR] faild to build tssrequest
> 
> Build 14C92 for device iPhone9,4 IS NOT being signed!

I get this error while trying to save shsh2 for my iPhone 7 Plus.

**Comment by grkka** [comment]
Me too on iPhone 6S Plus

**Comment by snowleopardw** [comment]
--boardconfig bdid → --boardconfig d10ap ( only iPhone 7 NOT Plus is this )
Check out the code ( Device Model ) using this app. http://itunes.apple.com/app/id1045029477

**Comment by tihmstar** [comment]
bdid is not a valid boardconfig.
As @snowleopardw already said, you need to specify a valid boardconfig
