### ISSUE TITLE
Apnoncelength fail

### ISSUE THREAD

**Issue by DaniWinter** [tihmstar/tsschecker#36]
[Error] [TSSR] parsed APNoncelen != requiredAPNoncelen (20 != 32)
[Error] [TSSR] failed to populate tss request
[Error] [TSSR] faild to build tssrequest

This is the latest TSSchecker build on Windows 10 using an iPhone 7 (GSM/iPhone9,3)

**Comment by DaniWinter** [comment]
Nevermind. Was using wrong apnonces.

**Comment by phonique** [comment]
Which ones did you end up using? I'm having the same issue.

**Comment by DaniWinter** [comment]
@phonique, I had only one collision on my iPhone 7, it was this nonce: ac13b71d60270bf2268afd616fa3e2ab769e2b1edaef366aa01b4f5d9bc9919c
