### ISSUE TITLE
undefined reference to `plist_dict_merge'

### ISSUE THREAD

**Issue by vec1phyr** [tihmstar/tsschecker#41]
Helllo tihmstar. In-attempt to reinstall tsschecker on a fresh WSL build, I've encountered this problem after running the make command. I'm not certain if you're aware of this issue already. Below is the make log before it fails (it's not the whole thing. If you want the whole thing, let me know. I can also send the stdout of autogen.sh)

Thanks.
---------------

tsschecker.h:63:19: warning: inline function ‘bbdevices_get_all’ declared but never defined [enabled by default]
mv -f .deps/tsschecker-main.Tpo .deps/tsschecker-main.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I/usr/include/libxml2   -I/usr/local/include     -I/usr/local/include -I/usr/include/libusb-1.0   -g -O2 -std=c11 -L/usr//usr/lib/x86_64-linux-gnu -lplist   -L/usr/local/lib -lfragmentzip -lz -lcurl   -lcurl   -lcrypto   -L/usr/local/lib -lirecovery   -lm  -o tsschecker tsschecker-tsschecker.o tsschecker-tss.o tsschecker-jsmn.o tsschecker-download.o tsschecker-main.o -L/usr//usr/lib/x86_64-linux-gnu -lplist   -L/usr/local/lib -lfragmentzip -lz -lcurl   -lcurl   -lcrypto   -L/usr/local/lib -lirecovery   -lm
libtool: link: gcc -I/usr/include/libxml2 -I/usr/local/include -I/usr/local/include -I/usr/include/libusb-1.0 -g -O2 -std=c11 -o tsschecker tsschecker-tsschecker.o tsschecker-tss.o tsschecker-jsmn.o tsschecker-download.o tsschecker-main.o  -L/usr//usr/lib/x86_64-linux-gnu -L/usr/local/lib -lplist /usr/local/lib/libfragmentzip.so -lz /usr/lib/x86_64-linux-gnu/libcurl.so -lcrypto /usr/local/lib/libirecovery.so -lm -pthread
tsschecker-tss.o: In function `tss_request_new':
/home/vec1phyr/tsschecker/tsschecker/tss.c:131: undefined reference to `plist_dict_merge'
tsschecker-tss.o: In function `tss_request_add_common_tags':
/home/vec1phyr/tsschecker/tsschecker/tss.c:429: undefined reference to `plist_dict_merge'
tsschecker-tss.o: In function `tss_request_add_ap_tags':
/home/vec1phyr/tsschecker/tsschecker/tss.c:579: undefined reference to `plist_dict_merge'
tsschecker-tss.o: In function `tss_request_add_baseband_tags':
/home/vec1phyr/tsschecker/tsschecker/tss.c:683: undefined reference to `plist_dict_merge'
collect2: error: ld returned 1 exit status
make[2]: *** [tsschecker] Error 1
make[2]: Leaving directory `/home/vec1phyr/tsschecker/tsschecker'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/vec1phyr/tsschecker'
make: *** [all] Error 2

**Comment by tihmstar** [comment]
please upload a full terminal log starting from the point where you clone this project, up to this error.
