### ISSUE TITLE
ERROR: device "iPhone9,2" is not in bbgcid.json

### ISSUE THREAD

**Issue by 0x2400** [tihmstar/tsschecker#42]
[Error] [TSSC] ERROR: device "iPhone9,2" is not in bbgcid.json, which means it's BasebandGoldCertID isn't documented yet.
If you own such a device please consider contacting @tihmstar to get instructions how to contribute to this project.

**Comment by bao3** [comment]
yes , I had the same problem for my iPad mini2 and my iPhone7

**Comment by frank89722** [comment]
iPhone9,4 have same issue

**Comment by tihmstar** [comment]
To get info about BasebandGoldCertID please take a look here: http://blog.tihmstar.net/2017/01/basebandgoldcertid-not-found-please.html
