### ISSUE TITLE
[Error] [TSSC] please specify an iOS version or buildID for this option..??

### ISSUE THREAD

**Issue by thisisALPINE** [tihmstar/tsschecker#44]
I have an iPhone 6S running iOS 10.0, and I run this command from my Mac (El Capitan): 

`sudo ./tsschecker_macos -d iPhone_4.7 -e myECIDxxx -s --save-path /path`

but I'm getting this error : 

`[TSSC] manually specified ecid to use, parsed "myECIDxxx" to dec:myECIDxxx
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] please specify an iOS version or buildID for this option
	use -h for more help`

The fact is that I can't find my iPhone model on https://www.theiphonewiki.com/wiki/Models . Can someone help me with that?

**Comment by derobi** [comment]
what device is that...you should use BMSSM from the app store to get your device id. once you do that then you save blobs with your board config

./tsschecker -d device mdl --boardconfig boardID -e deviceECID# -s --save-path ~/Desktop
