### ISSUE TITLE
*some* iPhone 5s nonce possible combinations seem to be <1000 and some are 16^40 combinations

### ISSUE THREAD

**Issue by neildufva** [tihmstar/tsschecker#51]
Does anyone know what makes some 5s nonce generations have lower possibilities like a 1 out of 1000 chance vs some 5s devices that have almost infinite possibilities? Is this the only device that has this type of potential and is it a chipset thing? (doesnt seem to be firmware related)

Just wondering if anyone had any idea what the differences are to why the nonce collision method would even work for certain devices... Thanks for any help!

**Comment by tihmstar** [comment]
Please only post issues here. If you want to discuss prometheus open a subreddit on /r/jailbreak and talk with people there
