### ISSUE TITLE
can not compile on CentOS 6.x . some library must be update, and CentOS not support c11 code. I release a version for CentOS 6.x.

### ISSUE THREAD

**Issue by hynnet** [tihmstar/tsschecker#55]
updated library:
libplist,  libirecovery, libfragmentzip, libxml2, libcurl

backup shsh command:
LD_LIBRARY_PATH=./ ./tsschecker -d iPhone8,1 -e 7D5C9000000 -i 10.2.1 -s --save-path shsh6s --boardconfig N00AP --nocache

[tsschecker_linux-170130.tar.gz](https://github.com/tihmstar/tsschecker/files/741821/tsschecker_linux-170130.tar.gz)

**Comment by tihmstar** [comment]
I don't really like seing some patched sourcecode in a zip here. Also i have no plans on backporting to pre c11 standards (although i don't think c11 is an actual issue on any OS). 
I havent tested tsschecker on CentOS 6, but if it actually doesn't work and you still want to support it, please fork the project, make a proper repo on git and add your patches there. Thank you.
