### ISSUE TITLE
"-list--devices" error code

### ISSUE THREAD

**Issue by CyberGhost84** [tihmstar/tsschecker#59]
i get this error in Terminal while trying to get the list of devices or iOS..

Version: 1f0dcf714dbcd0b01431d6b87030fe1573ec50e0 - 209
Segmentation fault: 11

any hint on that?
am i missing something?

thanks

**Comment by tihmstar** [comment]
Actually it's "--list-devices"
Since you specified only one "-" it was interpreted as "-l" which is "--latest"
Anyways, thanks for pointing out that segfault. Fixed in 7d267698cb16ab4699fa9cba20783ee041ac999e
