### ISSUE TITLE
[Error] [TSSC] parsing ota.json failed

### ISSUE THREAD

**Issue by adi2k17** [tihmstar/tsschecker#60]
When I try to download the IOS 10.3 beta shsh they give me this error [Error] [TSSC] parsing ota.json failed 

I use this command (-d iphone6,1 -i 10.3 --beta -o -e 526CB5878A2 -s)

**Comment by Siguza** [comment]
It has to be `iPhone6,1`, not `iphone6,1`.

That said, the OTA betas allow only "Upgrade"-style restores, whereas tsschecker defaults to "Erase"-style tickets and seems to lack a command line option to change that so far (until #62 gets merged).

**Comment by tihmstar** [comment]
since version c816c3f28c711004e4cd75e6671ef86bdc122da7 tsschecker also tries to save update ticket (even though it saves it in a way which futurerestore can't yet handle).
Also lowercase "iphone6,1" shouldn't be a problem anymore.
Be sure to use latest version of tsschecker
