### ISSUE TITLE
iPhone 6s - Build 14D27 (iOS 10.2.1) and 14E277 (iOS 10.3) - IS NOT being signed problem

### ISSUE THREAD

**Issue by barberagianluca** [tihmstar/tsschecker#63]
Hi, why do I get this error?

For version 10.2.1
`tsschecker_macos -d iPhone8,1 -e 376f451512c -i 10.2.1 --buildid 14D27 -s`

> Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
> [TSSC] manually specified ecid to use, parsed "376f451512c" to dec:3809439994156 hex:376f451512c
> [TSSC] opening firmware.json
> [JSON] counting elements
> [JSON] parsing elements
> [TSSC] got firmwareurl for iOS 10.2.1 build 14D27
> [TSSC] opening Buildmanifest for iPhone8,1_10.2.1_14D27
> [WARNING] can't unambiguously map model to boardconfig for device iPhone8,1
> [Error] [TSSR] cant find boardconfig for device=iPhone8,1 please manuall use --boardconfig
> [WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
> [WARNING] can't unambiguously map model to boardconfig for device iPhone8,1
> [Error] [TSSR] cant find boardconfig for device=iPhone8,1 please manuall use --boardconfig
> [Error] [TSSR] Error: could not get id0 for installType=Update
> [Error] [TSSR] faild to build tssrequest
>iOS 10.2.1 14D27 IS NOT signed!

> Build 14D27 for device iPhone8,1 IS NOT being signed!

For version 10.3
`tsschecker_macos -d iPhone8,1 -e 376f451512c -i 10.3 --buildid 14E277 -s`

> Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
> [TSSC] manually specified ecid to use, parsed "376f451512c" to dec:3809439994156 hex:376f451512c
> [TSSC] opening firmware.json
> [JSON] counting elements
> [JSON] parsing elements
> [TSSC] got firmwareurl for iOS 10.3 build 14E277
> [TSSC] opening Buildmanifest for iPhone8,1_10.3_14E277
> [LFZP] downloading BuildManifest.plist from http://appldnld.apple.com/ios10.3/091-02962-20170327-7584E8B4-0D86-11E7-B580-8CCE122AC769/iPhone_4.7_10.3_14E277_Restore.ipsw

> [Error] [LFZP] failed to open url
> [Error] [TSSC] ERROR: could not get BuildManifest for firmwareurl  http://appldnld.apple.com/ios10.3/091-02962-20170327-7584E8B4-0D86-11E7-B580-8CCE122AC769/iPhone_4.7_10.3_14E277_Restore.ipsw

> Build 14E277 for device iPhone8,1 IS NOT being signed!

Am I missing something? Thank you in advance!

P.S.
I'm not finding a boardconfig parameter for my iPhone, where can I find it?

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
Try the following:

tsschecker_macos -d iPhone8,1 -i 10.2.1 --boardconfig n71ap -e 376f451512c -s
tsschecker_macos -d iPhone8,1 -i 10.3 --boardconfig n71ap -e 376f451512c -s

(You shouldn't need the BuildID, by the way.)

**Comment by barberagianluca** [comment]
Thank you, the problem was the unnecessary -buildid parameter!

` tsschecker_macos -d iPhone8,1 -i 10.3 --boardconfig n71ap -e 376f451512c -s `
> Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
> [TSSC] manually specified ecid to use, parsed "376f451512c" to dec:3809439994156 hex:376f451512c
> [TSSC] opening firmware.json
> [JSON] counting elements
> [JSON] parsing elements
> [TSSC] got firmwareurl for iOS 10.3 build 14E277
> [TSSC] opening Buildmanifest for iPhone8,1_10.3_14E277
> [LFZP] downloading BuildManifest.plist from http://appldnld.apple.com/ios10.3/091-02962-20170327-7584E8B4-0D86-11E7-B580-8CCE122AC769/iPhone_4.7_10.3_14E277_Restore.ipsw
100 [===================================================================================================>]
> [TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
> [TSSR] Sending TSS request attempt 1... success
> also requesting APTicket for installType=Update
> [TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
> [TSSR] Sending TSS request attempt 1... success
> Saved shsh blobs!
> iOS 10.3 14E277 IS signed!
> 
> iOS 10.3 for device iPhone8,1 IS being signed!

[SOLVED]

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
No, I believe what solved it was using the "--boardconfig n71ap" parameter is what solved it as I tried it with the "--buildid 14E277" parameter and it still worked. It seems that that parameter is always needed when grabbing iPhone 6S blobs.
