### ISSUE TITLE
Error getting BasebandGoldCertID for iPhone5,1 and iPad2,2

### ISSUE THREAD

**Issue by mrdc** [tihmstar/tsschecker#65]
Hello,

I'm not able to save blobs for baseband for iPhone5,1 and iPad2,2 - having this issue: error getting BasebandGoldCertID.

iPhone 5,1 log:
`Version:` af9b9f2998bdeca7ece0829c2e718ae747745750 - 170
[TSSC] manually specified ecid to use, parsed "00000xxxxxxxxxxx" to dec:xxxxxxxxxxx hex:xxxxxxxxxxx
[TSSC] manually specified apnonce to use, parsed "9f4aeec726e7c682339ddb3c6c2dec
52662dc517" to hex:9f4aeec726e7c682339ddb3c6c2dec52662dc517
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] using cached Buildmanifest for iPhone5,1_10.2.1
[TSSC] opening bbgcid.json
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] parsing bbgcid.json failed!
[WARNING] [TSSR] WARNING: there was an error getting BasebandGoldCertID, continu
ing without requesting Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
Saved shsh blobs!

iOS 10.2.1 for device iPhone5,1 IS being signed!`

iPad 2,2 log:
`Version: af9b9f2998bdeca7ece0829c2e718ae747745750 - 170
[TSSC] manually specified ecid to use, parsed "00000xxxxxxxxxxx" to dec:xxxxxxxxxxx hex:xxxxxxxxxxx
[TSSC] manually specified apnonce to use, parsed "9f4aeec726e7c682339ddb3c6c2dec
52662dc517" to hex:9f4aeec726e7c682339ddb3c6c2dec52662dc517
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] using cached Buildmanifest for iPad2,2_13G36
[TSSC] opening bbgcid.json
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] parsing bbgcid.json failed!
[WARNING] [TSSR] WARNING: there was an error getting BasebandGoldCertID, continu
ing without requesting Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
Saved shsh blobs!

Build 13G36 for device iPad2,2 IS being signed!`

Both BasebandGoldCertID are in the tsschecker.c

Thanks!

**Comment by tihmstar** [comment]
Your using an outdated version of tsschecker

**Comment by mrdc** [comment]
With the latest build - v212 - tsschecker says that firmware "IS NOT being signed!", will post a log later.
v170 saves shsh but not for the baseband.

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
You should be using the latest version like so:

tsschecker -d iPhone5,1 -i 10.2.1 --apnonce 9f4aeec726e7c682339ddb3c6c2dec -e "[ECID]" -s
tsschecker -d iPad2,2 -i 9.3.5 --apnonce 9f4aeec726e7c682339ddb3c6c2dec -e "[ECID]" -s

Also, correct me if I'm wrong, but I believe @tihmstar will only provide support if you are using the latest version of tsschecker.

**Comment by mrdc** [comment]
Unfortunately, the latest version (212) is not working properly on Win7x64:
> [Error] [TSSC] ERROR: could not get BuildManifest for firmwareurl

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
Try this (with the latest version of tsschecker from http://api.tihmstar.net/builds/tsschecker/tsschecker-latest.zip):

tsschecker -d iPhone5,1 --apnonce 9f4aeec726e7c682339ddb3c6c2dec52662dc517 -e "[ECID]" -s -m iPhone5,1-10.2.1-BuildManifest.plist

tsschecker -d iPad2,2 --apnonce 9f4aeec726e7c682339ddb3c6c2dec52662dc517 -e "[ECID]" -s -m iPad2,2-9.3.5-BuildManifest.plist

Using these BuildManifest.plist's:

http://oothecapickle.tk/iPad2,2-9.3.5-BuildManifest.plist
http://oothecapickle.tk/iPhone5,1-10.2.1-BuildManifest.plist

(You can get BuildManifest's from extracted IPSW's; in other words, until this bug is fixed, you can just manually grab BuildManifest's)

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
@mrdc Did this work for you?

**Comment by mrdc** [comment]
@OothecaPickleGNUrmsTUXFSF
Thx, on my mac v212 works well for the iPhone, but not for the iPad 2,2.

Details:
https://github.com/tihmstar/tsschecker/issues/17

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
Do you have libimobiledevice installed? If so can you run ideviceinfo on your iPad and post the value of BasebandCertID?

**Comment by mrdc** [comment]
@OothecaPickleGNUrmsTUXFSF 
Don't have it, but going to install :)

**Comment by mrdc** [comment]
@OothecaPickleGNUrmsTUXFSF 
P.S. Will you be so kind to provide me the latest complied build?

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
http://api.tihmstar.net/builds/tsschecker/tsschecker-latest.zip

**Comment by mrdc** [comment]
oh, i mean libimobiledevice.

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
For Windows or macOS?

**Comment by mrdc** [comment]
macos

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
you have homebrew? if not, that's fine, it would just make it easier to have homebrew

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
You can get the latest build from [here](https://github.com/libimobiledevice/libimobiledevice)

**Comment by mrdc** [comment]
yeah, I know where it is and I've also briefly searched for compiled build, but sources are not trustful.
The reason I've asked about compiled build is that my mac is not dev machine, so don't want to install extra software just to compile it... Homebrew I've had on my old and dead maс :)
