### ISSUE TITLE
failed to download file <-10>

### ISSUE THREAD

**Issue by leuldereje** [tihmstar/tsschecker#68]
![capture](https://cloud.githubusercontent.com/assets/18234761/24591127/f4552d1c-1802-11e7-8198-b89caded75aa.JPG)

**Comment by leuldereje** [comment]
just checked and it works on v184. (if this info helps you)

**Comment by theindian435** [comment]
Hi,

Same problem with v212 on Windows, but worked with v170;
v212 work on my MacOS in VM;
You specify to try v184, where is this version?

Thk

**Comment by leuldereje** [comment]
I download it long ago when it was released. but if your rlly want it, I have uploaded it to you.
Google Drive: https://drive.google.com/file/d/0B5wyPagB-H5BRE44Z1NYR2lhUTA/view?usp=sharing

**Comment by tihmstar** [comment]
same as #47

**Comment by leuldereje** [comment]
you really cant blame him. tsschecker is a tool that needs a continuous development and we should start appreciating him for what he have done thus far.

In addition, he also made it open sourced so that other dev can fork and maintain it like what firstecounter is doing.
