### ISSUE TITLE
[Error] [TSSR] ERROR: Unable to add img4 tags to TSS request (new version)

### ISSUE THREAD

**Issue by Yzord** [tihmstar/tsschecker#77]
I am still having this issue though

> [TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 10.3.1 build 14E304
[TSSC] opening Buildmanifest for iPhone9,4_10.3.1_14E304
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[Error] [TSSR] ERROR: Unable to add img4 tags to TSS request
Saved shsh blobs!
iOS 10.3.1 14E304 IS signed!

**Comment by barberagianluca** [comment]
compiled build is still on version 220
