### ISSUE TITLE
tsschecker v220 (windows) - iOS 10.3.1 for device iPhone7,2 IS NOT being signed!

### ISSUE THREAD

**Issue by 877cms** [tihmstar/tsschecker#80]
Same issue as I previously reported with more information, using latest v220. The commands used are below and all work fine (copied and pasted) with v170 but not with v212. I have obscured ECID but it is 100% correct:

**C:\tsschecker-latest>tsschecker_windows -B N61AP -e XXXXXXXXXXXX -i 10.3.1 -s
Version: c7a07b3b88d10ff828f277af4959f9b6afcdff02 - 220
[TSSC] manually specified ecid to use, parsed "XXXXXXXXXXXX" to dec:XXXXXXXXhex:XXXXXXXX
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 10.3.1 build 14E304
[TSSC] opening Buildmanifest for iPhone7,2_10.3.1_14E304
[LFZP] downloading BuildManifest.plist from http://appldnld.apple.com/ios10.3.1/091-07017-20170403-3B0415D4-16E1-11E7-A3C8-2D4C132AC769/iPhone_4.7_10.3.1_14E304_Restore.ipsw

[A[J100 [===================================================================================================>]
[A[J015 [==============>                                                                                     ]
[A[J066 [=================================================================>                                  ]
[A[J085 [====================================================================================>               ]
[A[J100 [===================================================================================================>]
[Error] [LFZP] failed to download file (-10)
[Error] [TSSC] ERROR: could not get BuildManifest for firmwareurl http://appldnld.apple.com/ios10.3.1/091-07017-20170403-3B0415D4-16E1-11E7-A3C8-2D4C132AC769/iPhone_4.7_10.3.1_14E304_Restore.ipsw

iOS 10.3.1 for device iPhone7,2 IS NOT being signed!**

I also tried the following commands which again work with v170 but not with v212 or v220:
(again I replaced ECID with XXXXXXXXX but I am sure syntax was correct)

**tsschecker_windows -B N61AP -e XXXXXXXXXX -i 10.3.1 -s --apnonce 603be133ff0bdfa0f83f21e74191cf6770ea43bb
tsschecker_windows -B N61AP -e XXXXXXXXXX -i 10.3.1 -s --apnonce 352dfad1713834f4f94c5ff3c3e5e99477347b95
tsschecker_windows -B N61AP -e XXXXXXXXXX -i 10.3.1 -s --apnonce 42c88f5a7b75bc944c288a7215391dc9c73b6e9f
tsschecker_windows -B N61AP -e XXXXXXXXXX -i 10.3.1 -s --apnonce 9804d99e85bbafd4bb1135a1044773b4df9f1ba3
tsschecker_windows -d iPhone7,2 -e XXXXXXXXXX -i 10.3.1 --buildid 14E304 -s**

Many thanks for this great project and let me know if I can test any other commands.

**Comment by 877cms** [comment]
Reading further it seems that downloading IPSW file and using -m might help, could anyone provide a sample usage of this command?

**Comment by goodboydheeraj** [comment]
You can use http://wobzip.org/ to download only the buildmanifest.plist file! This site downloads the whole ipsw and unzips it so you can download only what you need from the firmware file!

**Comment by 877cms** [comment]
@goodboyheeraj thanks for the tip

**Comment by OothecaPickle** [comment]
or you can simply use [partialZipBrowser](https://github.com/tihmstar/partialZipBrowser)

**Comment by OothecaPickle** [comment]
Also, there is a known issues with libfragmentzip on Windows, which results in Windows useres having to manually specify a BuildManifest.plist.

tsschecker_windows -d iPhone7,2 --boardconfig n61ap -e [ECID] -m BuildManifest.plist

**Comment by 877cms** [comment]
@OothecaPickle Thanks for the info :)

**Comment by OothecaPickle** [comment]
did you get it to work though?

**Comment by 877cms** [comment]
Oh sorry I forgot to say :)
Yes it worked thank you.

**Comment by OothecaPickle** [comment]
great!

**Comment by tihmstar** [comment]
same as #47
