### ISSUE TITLE
iPad Mini 3 wifi - If you own such a device please consider contacting @tihmstar to get instructions how to contribute to this project.

### ISSUE THREAD

**Issue by 877cms** [tihmstar/tsschecker#81]
I'm posting this to offer my help if needed as per the error message:

C:\tsschecker220>tsschecker_windows -d iPad4,7 -e XXXXXXXX-i 10.3.1 --buildid 14E304 -s -m BuildManifest.plist
Version: c7a07b3b88d10ff828f277af4959f9b6afcdff02 - 220
[TSSC] manually specified ecid to use, parsed "XXXXXXXX" to dec:XXXXXXXXhex:XXXXXXXX
[TSSC] opening BuildManifest.plist
[Error] [TSSC] ERROR: device "iPad4,7" is not in bbgcid list, which means it's BasebandGoldCertID isn't documented yet.
If you own such a device please consider contacting @tihmstar to get instructions how to contribute to this project.
[WARNING] [TSSR] there was an error getting BasebandGoldCertID, continuing without requesting Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[Error] [TSSC] ERROR: device "iPad4,7" is not in bbgcid list, which means it's BasebandGoldCertID isn't documented yet.
If you own such a device please consider contacting @tihmstar to get instructions how to contribute to this project.
[WARNING] [TSSR] there was an error getting BasebandGoldCertID, continuing without requesting Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[Error] [TSSR] ERROR: Unable to add img4 tags to TSS request
Saved shsh blobs!

Build 14E304 for device iPad4,7 IS being signed!

**Comment by OothecaPickle** [comment]
You don't need to do anything, because the BasebandGoldCertID for WiFi-only iDevices is always zero as they don't have a baseband.

**Comment by 877cms** [comment]
@OothecaPickle makes sense, if it's not helpful then I guess this may as well be closed.

**Comment by OothecaPickle** [comment]
ya, i already submitted a pull request. if you don't want to see that error message again you can use the [pulls branch of my tsschecker fork](https://github.com/OothecaPickle/tsschecker/tree/pulls)

**Comment by OothecaPickle** [comment]
i didn't post an exe; you'd have to compile it yourself. also, i noticed that you forked my fork of tsschecker, but you forked the master branch, which has not yet been merged with the pulls branch of my fork which contains the changes you want. also, you shouldn't need to fork it all, just download [this](https://github.com/OothecaPickle/tsschecker/archive/pulls.zip)

**Comment by 877cms** [comment]
OK i'll have a look thanks for you help!!

**Comment by OothecaPickle** [comment]
as for building it, you should take a look at tihmstar's build instructions [here](https://github.com/tihmstar/tsschecker/tree/master/BUILD)

**Comment by OothecaPickle** [comment]
i can't really help you out much with that as i don't have access to a windows machine at the moment, but i hope you're able to figure it out

**Comment by 877cms** [comment]
Brilliant thank you, I'm sure I'll figure it out eventually :)

**Comment by OothecaPickle** [comment]
alright, really sorry about this but forget everything i just said. use the [master branch of my fork](https://github.com/OothecaPickle/tsschecker) as it's build.txt is updated to download my  update tsschecker instead of tihmstar's.

**Comment by OothecaPickle** [comment]
Alright, my pull request has been merged, so just download the master branch of tsschecker from [here](https://github.com/tihmstar/tsschecker/archive/master.zip) and follow tihmstar's build instructions [here](https://github.com/tihmstar/tsschecker/tree/master/BUILD).

**Comment by OothecaPickle** [comment]
the compiled build [here](http://api.tihmstar.net/builds/tsschecker/tsschecker-latest.zip) has been updated, so no need to compile it yourself
