### ISSUE TITLE
--buildid arg not working

### ISSUE THREAD

**Issue by iApeiron** [tihmstar/tsschecker#85]
cb5d1308ad274ef02c42b4cb0cb67c64c1bfc553 introduced the bug.
Previous commit c8a1c07fd6de65ca79bc7cf51324212de7203203 works fine.

**Comment by tihmstar** [comment]
fixed. can you check with at least version eb6f771c1fefdb09c988116de991e6aa1f7d8d8e ? :)

**Comment by iApeiron** [comment]
--buildid now works as expected for currently signed firmware versions. Thank you.

**Comment by SJ50** [comment]
Not working with Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
Linux build
