### ISSUE TITLE
iOS 10.3.1 for device iPad4,4 IS NOT being signed!

### ISSUE THREAD

**Issue by 2CAN0** [tihmstar/tsschecker#88]
How can I fix this error, because as far as ik ios 10.3.1 is the latest and still being signed

![image](https://cloud.githubusercontent.com/assets/26686369/26032147/04ffa97c-388c-11e7-8633-54ac25911d29.png)

**Comment by iFred09** [comment]
The libfragmentzip has a little problem on precompiled version for Windows. You can compile yourself tsschecker and libfragmentzip, or you can use -m and specify the BuildManifest.plist

**Comment by tihmstar** [comment]
same as #47
