### ISSUE TITLE
Windows version not work

### ISSUE THREAD

**Issue by iFred09** [tihmstar/tsschecker#9]
Hi, tsschecker for windows don't work, the terminal send me a error : "[TSSC] parsing firmware.json failed"
Tested on Windows 7 on Cmder and cmd.exe

**Comment by capsload** [comment]
Same for me. The firmware.json seems to missing!

**Comment by NickFlamel** [comment]
[TSSC] manually specified ecid to use, parsed "5F4F18E2C30" to dec:6549582785584 hex:5f4f18e2c30
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[Error] failed to download file from=https://api.ipsw.me/v2.1/firmwares.json/condensed to=C:\Users\NICK_F~1\AppData\Local\Temp\firmware,json CURLcode=77
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] parsing firmware.json failed

**Comment by FNCxPro** [comment]
Short term solution: go to ```%temp``` in Windows and find ```firmware.json```. After that, go to https://api.ipsw.me/v2.1/firmwares.json/condensed and copy everything on that page. Then edit firmware.json with a text editor like Notepad++ and paste everything from that page into that document and save.

**Comment by tihmstar** [comment]
Download the Windows version from the link in the README.
When you unzip it you should have the exe as well as a file called cacert.pem. 
That one is complied so it searches for a cacert.pem in the same directory as the exe, so make sure you have both files in the same directory. 
That should resolv the CURL error. 
Try also adding --nocache so it deletes the cached files and redownloads them.
