### ISSUE TITLE
iOS 10.3.2 14F89 IS NOT signed! 

### ISSUE THREAD

**Issue by ScknCbt** [tihmstar/tsschecker#90]
MacBookPro:tsschecker ScknCbt$ tsschecker -d iPhone9,4 -e ECID# -l -s
Version: dd83e1797c5bc0ffaa84730f69530b5524a49051 - 240
[TSSC] manually specified ecid to use, parsed "##" to dec:## hex:##
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest iOS: 10.3.2
[TSSC] got firmwareurl for iOS 10.3.2 build 14F89
[TSSC] opening Buildmanifest for iPhone9,4_10.3.2_14F89
[LFZP] downloading BuildManifest.plist from http://appldnld.apple.com/ios10.3.2/031-98958-20170515-E1FEB802-2F92-11E7-8632-F3688FB7FE33/iPhone_7Plus_10.3.2_14F89_Restore.ipsw
100 [===================================================================================================>]
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[TSSR] Request URL set to https://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 2... failure
[TSSR] Request URL set to https://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 3... failure
[TSSR] Request URL set to http://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 4... failure
[TSSR] Request URL set to http://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 5... failure
[TSSR] Request URL set to http://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 6... failure
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 7... failure
[TSSR] Request URL set to https://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 8... failure
[TSSR] Request URL set to https://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 9... failure
[TSSR] Request URL set to http://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 10... failure
[TSSR] Request URL set to http://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 11... failure
[TSSR] Request URL set to http://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 12... failure
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 13... failure
[TSSR] Request URL set to https://17.111.103.65/TSS/controller?action=2
[TSSR] Sending TSS request attempt 14... failure
[TSSR] Request URL set to https://17.111.103.15/TSS/controller?action=2
[TSSR] Sending TSS request attempt 15... failure
iOS 10.3.2 14F89 IS NOT signed!

iOS 10.3.2 for device iPhone9,4 IS NOT being signed!

**Comment by tihmstar** [comment]
This seems to be baseband related. I pushed a hotfix in 8d7649c9fd0d7d43ceab5c6974f16411e460188b by removing baseband gold cert id from database.
Baseband tickets aren't used by any tool anyways, so it's not a big deal not saving baseband tickets.
This should however allow saving regular APTickets with default parameters (without -b flag)

**Comment by encounter** [comment]
I fixed this issue in https://github.com/encounter/tsschecker/commit/35c62b4837a387cec6e862e8080d1b61257b2195. Root cause was the `strcasecmp`. Cleaned up the surrounding code a bit too.
