### ISSUE TITLE
Windows executable missing from latest compiled download (Sep 15)

### ISSUE THREAD

**Issue by timidhermit** [tihmstar/tsschecker#97]
Did anyone notice that the Windows executable is missing from the latest compiled download (as of September 15, 2017) in the readme section? Only Mac and Linux compiled builds were there. Is this absence intentional? I am looking for the latest Windows compiled build, as version 170 no longer works and gives error in downloading the BuildManifest.

Anyone help?

**Comment by timidhermit** [comment]
Can anyone please help to post a link to the Windows compiled build of the latest version of tsschecker? No one else seems to be looking at the post.

**Comment by 2Klasic** [comment]
i dont know if there is a latest compiled version of windows to be honest

**Comment by Fredric27** [comment]
Sapete , è successo anche a me !
