### ISSUE TITLE
Please release update version on http://api.tihmstar.net/builds/tsschecker/tsschecker-latest.zip

### ISSUE THREAD

**Issue by kamakuba** [tihmstar/tsschecker#98]
Please release update version on http://api.tihmstar.net/builds/tsschecker/tsschecker-latest.zip

**Comment by kamakuba** [comment]
or PLS provide detailed instruction how to build it by myself

**Comment by vrtxf** [comment]
Which platform are you looking for ? there is xcode project there for macos and a makefile. Can't help much with windows

**Comment by kamakuba** [comment]
for linux
