### ISSUE TITLE
tsschecker depends on libssl 1.0.0

### ISSUE THREAD

**Issue by waja** [tihmstar/tsschecker#99]
When running on Debian stable:

```./tsschecker: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory```

No, ```libcrypto.so.1.0.0``` is not available there, have a look into [packages.debian.org](https://packages.debian.org/search?suite=stretch&arch=any&mode=exactfilename&searchon=contents&keywords=libcrypto.so.1.0.0).

It would be very welcome to find a solution for this, as Debian derivates (like Ubuntu) would be affected as well when making use of openssl 1.1.0.

Many thanks, Jan.

**Comment by waja** [comment]
Anyway, recent Fedora uses AFAIK also openssl 1.1.0, but I've no glue if they provide openssl 1.0.0 as well.

**Comment by ann0see** [comment]
Same "problem" here. Symbolic link from libcrypto 1.1 or 1.0.something to libcrypto 1.0.0 doesn't work. 

Debian 9

**Comment by bamtan** [comment]
bump

**Comment by 1Conan** [comment]
libcrypto 1.1 isn't compatible with libcrypto 1.0 so sym linking wont work.

You could install this package and check if it works. https://packages.debian.org/stretch/libssl1.0.2

**Comment by Nosskirneh** [comment]
If anyone on Arch comes across this issue, install `openssl-1.0` (`pacman -S openssl-1.0` should do it).

**Comment by palmerc** [comment]
Try switching to [libressl](https://www.libressl.org) is is header-compatible with OpenSSL 1.0 and built with CMake allowing easy cross-platform compilation

**Comment by jkister** [comment]
> You could install this package and check if it works. https://packages.debian.org/stretch/libssl1.0.2

```
# aptitude search libssl1 | awk '{print $1" "$2}'
p libssl1.0-dev
i libssl1.0.2
i libssl1.1
# tsschecker_linux 
tsschecker_linux: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
# cd /usr/lib/x86_64-linux-gnu/
# ls -ld libcrypto.so.1*
-rw-r--r-- 1 root root 2500448 Feb 27 15:58 libcrypto.so.1.0.2
-rw-r--r-- 1 root root 2711616 Nov 28 17:43 libcrypto.so.1.1
# ln -s libcrypto.so.1.0.2 libcrypto.so.1.0.0
# tsschecker_linux 
tsschecker_linux: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by tsschecker_linux)
```

i have other things depending on 1.1; not easy to remove.  thoughts?

**Comment by 1Conan** [comment]
libssl1.0.2 doesn’t conflict with 1.1 iirc

Use LD_PRELOAD or compile it while linking to 1.0.2. 
Messing with the libraries outside of the packagemanager is just messy.
